### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by AndrewJo** [masasron/adonis-throttle#10]
I think we can have two CI pipelines: one for continuous testing on feature branches and the other for automatic deployment whenever a new version is published via `npm version`.

I'm most experience with CircleCI but I've used TravisCI in the past too.

Here's what I did for `adonis-compression` provider: 

https://github.com/VerdigrisTech/adonis-compression/blob/master/.circleci/config.yml

**Comment by masasron** [comment]
Okay, after much trial and error I think I got it 😄 

Please let me know if you see anything I need to change.

Thanks,
Ron

**Comment by AndrewJo** [comment]
Looks awesome @masasron! 🚀 

Quick tip, if you want your CI badge to look consistent in your README.md, shields.io provides a CircleCI compatible badge as well:

```md
[![CircleCI](https://img.shields.io/circleci/project/github/masasron/adonis-throttle.svg)](https://circleci.com/gh/masasron/adonis-throttle)
```

Which will render a badge that looks consistent with rest of your badges:

[![CircleCI](https://img.shields.io/circleci/project/github/masasron/adonis-throttle.svg)](https://circleci.com/gh/masasron/adonis-throttle)

I think we can eventually integrate code coverage with [`nyc`](https://github.com/istanbuljs/nyc) and [Codecov](//codecov.io) to make sure further changes are covered by tests.

**Comment by masasron** [comment]
Cool, I've updated the badge.

Thank you @AndrewJo
