### ISSUE TITLE
Make sure Adonis/Addons/Throttle does have a extend method. Report this issue to the provider author > More details: https://err.sh/adonisjs/errors/E_INVALID_IOC_MANAGER

### ISSUE THREAD

**Issue by jericopulvera** [masasron/adonis-throttle#11]
InvalidArgumentException: E_INVALID_IOC_MANAGER: Make sure Adonis/Addons/Throttle does have a extend method. Report this issue to the provider author
> More details: https://err.sh/adonisjs/errors/E_INVALID_IOC_MANAGER

at /Users/eco/Code/api.jericopulvera.com/server.js(anonymous):24
19  
20  const { Ignitor } = require('@adonisjs/ignitor')
21  
22  new Ignitor(require('@adonisjs/fold'))
23    .appRoot(__dirname)
24    .fireHttpServer()
25    .catch(console.error)

**Comment by masasron** [comment]
@AndrewJo any ideas?

**Comment by jericopulvera** [comment]
It's working before but now it's not. Maybe because of adonis update?

**Comment by barryrld** [comment]
I came across this earlier today too.

I've been able to fix it locally so I've created a pull request that provides the fix and updates the associated test.

I've provided more detail in the PR: https://github.com/masasron/adonis-throttle/pull/12

Let's await feedback from the maintainers to see whether this PR is appropriate and whether they agree to merge it in.

Many thanks!

**Comment by AndrewJo** [comment]
Oof. Just saw this now (just flew out for my wedding so haven't been checking my email) My bad guys. I should've tested it more thoroughly with a sample AdonisJs project. I'll review @barryld's PR #12 and perhaps set up an integration test so we can catch things like this before it makes it into the codebase. Again, sorry and I take full responsibility for this bug.

**Comment by masasron** [comment]
I've merged the fix, should be okay now 👍

**Comment by barryrld** [comment]
Congratulations to @AndrewJo. I hope everything went well for you.

Bugs happen - it's just software. Life is more important. I hope you're not being too hard on yourself!

Thanks @masasron and @AndrewJo for attending to this and merging in the changes. Also, thanks for all your work on this project.

**Comment by masasron** [comment]
Great work everyone!

Congratulations @AndrewJo 🎉 as @barryld said it’s all good!
