### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by kennedyrs** [masasron/adonis-throttle#16]
When I try to use it with Redis, I have this error

```json
{
  "status": 500,
  "name": "TypeError",
  "message": "this.throttle.store.secondsToExpiration is not a function"
}
```

Node v12.14.1
Adonis 4.1

is this an error or am I missing something?

**Comment by masasron** [comment]
@AndrewJo could you take a look?

**Comment by kennedyrs** [comment]
At file adonis-throttle/middleware/ThrottleRequests.js they try to add a header  `this.throttle.store.secondsToExpiration(this.throttle.key)`
```js
if (!this.throttle.attempt()) {
            this.throttle.incrementExpiration()
            this._addHeaders(
                response,
                maxAttempts,
                this.throttle.remainingAttempts(),
                this.throttle.store.secondsToExpiration(this.throttle.key)
            )
            throw new TooManyRequestsException('Too Many Attempts.')
        }
```

but at adonis-throttle/src/Drivers/Cache/Redis/index.js this function does not exists

**Comment by AndrewJo** [comment]
@masasron @kennedyrs submitted PR #17 that fixes this issue!

**Comment by masasron** [comment]
Great, thank you @AndrewJo
