### ISSUE TITLE
does this throttle by Ip or the session?

### ISSUE THREAD

**Issue by pixelpaulaus** [masasron/adonis-throttle#23]
Does this throttle by the IP or the session?
If by the session, couldn't the user just start a new one and bypass it.
If by the IP, where does it get the IP? As i have my adonis behind a proxy and the end user IP is passed on a customer request header.

**Comment by SimenCodes** [comment]
New to this library too, but it seems to throttle by request signature. With the default settings, I can bypass it by simply modifying the request path. For example the route `/login` has 2⁵ combinations of upper- and lowercase letters, giving each client 32 times the number of attempts you configure (edit: assuming your routing setup is not case sensitive). The comment in #7 seems to confirm this and suggests https://github.com/masasron/adonis-throttle#advanced-usage to customize the behavior.

**Comment by masasron** [comment]
@SimenCodes Nice catch, I think I'll change that to be on the strict side by normalizing the path.
@pixelpaulaus here is the default request signature we use https://github.com/masasron/adonis-throttle/blob/master/middleware/ThrottleRequests.js#L71 we get the IP using the `Request.ip()` method.

It seems to support proxy servers when you set trustProxy to true in `config/app.js` and set `X-forwarded-*` headers in your proxy. see https://forum.adonisjs.com/t/request-ip-question/2155/4

So you could do that, or as @SimenCodes suggested create your own request signature according to your specific needs.

**Comment by pixelpaulaus** [comment]
sorry, i could not see a way to implement a custom signature function. could you please provide an quick example?

**Comment by masasron** [comment]
https://github.com/masasron/adonis-throttle#advanced-usage

**Comment by pixelpaulaus** [comment]
so is it only possible within the controller itself and not as a middleware? as per the advanced usage.

**Comment by masasron** [comment]
No, you can also do it in your own middleware.
Example: https://github.com/masasron/adonis-throttle/blob/master/middleware/ThrottleRequests.js
