### ISSUE TITLE
maxAttempts is Array, not number

### ISSUE THREAD

**Issue by ntvsx193** [masasron/adonis-throttle#5]
![image](https://user-images.githubusercontent.com/2971095/38328459-ad647e22-3853-11e8-86cc-a9377d27a0f7.png)

```javascript
Route.post('/auth', 'AuthController.login')
  .validator('Auth/Login')
  .middleware(['throttle'])
```

**Comment by ntvsx193** [comment]
Maybe it's breaking changes from version 4.1.
It's work correctly ```
async handle({request, response}, next, [ maxAttempts = 60, decayInSeconds = 60 ], uid = false) {
```

**Comment by masasron** [comment]
@ntvsx193 thanks!
