### ISSUE TITLE
Cannot find module '@adonisjs/fold'

### ISSUE THREAD

**Issue by goper-leo** [masasron/adonis-throttle#8]
I'm using adonis-js @3.2.1 and use `adonis-throttle@2.0` as per the docs says. 

Now there is error in `ThrottleProvider.js` about on line 12 
`const { ServiceProvider } = require('@adonisjs/fold')` 
error says 
`Cannot find module '@adonisjs/fold'`.

**Comment by masasron** [comment]
I tested the package on a fresh copy of Adonis and it works fine.
Try repeating the steps and or reinstall dependencies on your project.
